---
# Source: helm for kubernetes/templates/application.yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: "modern-ux-ui-37348950"
  namespace: "argocd"
spec:
  project: default
  source:
    repoURL: https://github.com/BunathPheng/modern-ux-ui-37348950-manifests.git
    targetRevision: HEAD
    path: manifests
  destination:
    server: https://kubernetes.default.svc
    namespace: smartops-api
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
